/* global Ext */
Ext.Future.lang = {
    lbAdd: 'Adicionar',
    lbAdd2: 'Adicionar {0}',
    lbMod: 'Modificar',
    lbMod2: 'Modificar {0}',
    lbDel: 'Eliminar',
    lbDel2: 'Eliminar {0}',
    lbPrint: 'Imprimir',
    lbPrint2: 'Imprimir listado de {0}',
    lbSearch: 'Buscar',
    lbSearch2: 'Buscar {0}',
    lbApply: 'Aplicar',
    lbApply2: 'Guardar datos y limpiar los campos',
    lbAccept: 'Aceptar',
    lbAccept2: 'Guardar datos y cerrar ventana',
    lbCancel: 'Cancelar',
    lbCancel2: 'Cerrar ventana sin guardar datos',
    lbLoading: 'Cargando...',
    lbLoading2: 'Cargando {0}',
    lbSaving: 'Guardando...',
    lbSaving2: 'Guardando {0}',
    lbUpdate: 'Actualizar',
    lbWait: 'Por favor espere...',
    lbSelect: 'Seleccione {0}',
    lbCriteria: 'Criterio a buscar',
    lbDescription: 'Descripci\xF3n',
    lbInformation: 'Informaci\xF3n',
    lbConfirmation: 'Confirmaci\xF3n',
    lbError: 'Error',
    lbNoResults: 'No hay resultados para mostrar.',
    lbGroupTextTpl: '{text} ({[values.rs.length]} {[values.rs.length > 1 ? {0} : {1}]})',
    lbGroupTextTpl2: '{text} ({[values.rs.length]} en total)',
    lbInvalidForm: 'Por favor verifique nuevamente que hay campo(s) con valor(es) incorrecto(s).',
    lbConfirmDel: '&iquest;Est&aacute; seguro que quiere eliminar el {0} seleccionado?',
    lbConfirmDel2: '&iquest;Est&aacute; seguro que quiere eliminar la {0} seleccionada?',
    lbSelMod: 'Debe seleccionar el {0} que quiere modificar',
    lbSelMod2: 'Debe seleccionar la {0} que quiere modificar',
    lbSelDel: 'Debe seleccionar el {0} que quiere eliminar',
    lbSelDel2: 'Debe seleccionar la {0} que quiere eliminar',
    lbAddOk: 'El {0} fue adicionado correctamente',
    lbAddOk2: 'La {0} fue adicionada correctamente',
    lbModOk: 'El {0} fue modificado correctamente',
    lbModOk2: 'La {0} fue modificada correctamente',
    lbDelOk: 'El {0} fue eliminado correctamente',
    lbDelOk2: 'La {0} fue eliminada correctamente',
    lbErrorServer: 'En estos momentos el servidor no ha podido responder la petici&oacute;n realizada. Contacte con el proveedor de soporte, por favor.'
};
