/* global Ext */
Ext.Future.lang = {
    lbAdd: 'Add',
    lbAdd2: 'Add {0}',
    lbMod: 'Modify',
    lbMod2: 'Modify {0}',
    lbDel: 'Delete',
    lbDel2: 'Delete {0}',
    lbPrint: 'Print',
    lbPrint2: 'Print list of {0}',
    lbSearch: 'Search',
    lbSearch2: 'Search {0}',
    lbApply: 'Apply',
    lbApply2: 'Save data and reset fields',
    lbAccept: 'Ok',
    lbAccept2: 'Save data and close window',
    lbCancel: 'Cancel',
    lbCancel2: 'Close window without save data',
    lbLoading: 'Loading...',
    lbLoading2: 'Loading {0}',
    lbSaving: 'Saving...',
    lbSaving2: 'Saving {0}',
    lbUpdate: 'Update',
    lbWait: 'Please wait...',
    lbSelect: 'Select {0}',
    lbCriteria: 'Search criterion',
    lbDescription: 'Description',
    lbInformation: 'Information',
    lbConfirmation: 'Confirmation',
    lbError: 'Error',
    lbNoResults: 'There are not data to display.',
    lbGroupTextTpl: '{text} ({[values.rs.length]} {[values.rs.length > 1 ? {0} : {1}]})',
    lbGroupTextTpl2: '{text} ({[values.rs.length]} items)',
    lbInvalidForm: 'Please verify again that there is field (s) with (it is) incorrect value (s).',
    lbConfirmDel: 'Are you sure that you want to delete the selected {0}?',
    lbConfirmDel2: 'Are you sure that you want to delete the selected {0}?',
    lbSelMod: 'You must select the {0} that you want to modify',
    lbSelMod2: 'You must select the {0} that you want to modify',
    lbSelDel: 'You must select the {0} that you want to delete',
    lbSelDel2: 'You must select the {0} that you want to delete',
    lbAddOk: 'The {0} was added correctly',
    lbAddOk2: 'The {0} was added correctly',
    lbModOk: 'The {0} was modified correctly',
    lbModOk2: 'The {0} was modified correctly',
    lbDelOk: 'The {0} was deleted correctly',
    lbDelOk2: 'The {0} was deleted correctly',
    lbErrorServer: 'Error processing data. <br/>Contact with the administrator of the system.'
};
