<html>
    <head>
        <meta charset="UTF-8" />
        <link rel="stylesheet" type="text/css" href="<?php echo $this->extcss; ?>"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->libcss; ?>fonts/FontAwesome/css/font-awesome.min.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->libjs; ?>Extjs/2.2/resources/css/iconos.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->libjs; ?>Extjs/2.2/resources/css/colorfila.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->libjs; ?>Bootstrap/css/bootstrap-elements.css"/>
    </head>
    <body>
        <script type="text/javascript"> var globalAuthToken = '<?php echo $this->futureToken; ?>';</script>
        <script language="javascript" type="text/javascript">function sin_foto() {
                return '<?php echo $this->libjs . 'Extjs/2.2/resources/images/no-picture.png'; ?>';
            }</script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/ext/ext-base.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/ext/ext-all.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/components/grid/PagingToolbar/Ext.Feet.PagingToolbar.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/components/form/SearchField/Ext.form.SearchField.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/lang/ext-lang-<?php echo $this->lang; ?>.js"></script>
        <script type="text/javascript" src="<?php echo $this->viewjs; ?>/views/lang/<?php echo $this->lang; ?>/usuarios.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/ext/funciones-utiles.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Utils/Base64cypt.js"></script>
        <script type="text/javascript" src="<?php echo $this->viewjs; ?>/views/js/usuarios/usuarios.js"></script>
    </body>
</html>