<!DOCTYPE html>
<head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->extcss; ?>" media="screen"/>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->libcss; ?>fonts/FontAwesome/css/font-awesome.min.css"/>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->libcss; ?>ff/matrix.css"/>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->extver; ?>components/BubbleMsg/Ext.BubbleMsg.min.css"/>
    <style type="text/css">
        #images-view .x-panel-body {
            background: white;
            font: 11px Arial, Helvetica, sans-serif;
        }

        #images-view .thumb {
            background: #dddddd;
            padding: 3px;
            padding-bottom: 0;
        }

        .x-quirks #images-view .thumb {
            padding-bottom: 3px;
        }

        #images-view .thumb img {
            height: 60px;
            width: 80px;
        }

        #images-view .thumb-wrap {
            float: left;
            margin: 4px;
            margin-right: 0;
            padding: 5px;
        }

        #images-view .thumb-wrap span {

            display: block;
            overflow: hidden;
            text-align: center;
            width: 86px; /* for ie to ensure that the text is centered */
        }

        #images-view .x-item-over {
            border: 1px solid #dddddd;
            background: #efefef url(over.gif) repeat-x left top;
            padding: 4px;
        }

        #images-view .x-item-selected {
            background: #eff5fb url(selected.gif) no-repeat right bottom;
            border: 1px solid #99bbe8;
            padding: 4px;
        }

        #images-view .x-item-selected .thumb {
            background: transparent;
        }

        #images-view .loading-indicator {
            font-size: 11px;
            background-image: url('../../resources/themes/images/default/grid/loading.gif');
            background-repeat: no-repeat;
            background-position: left;
            padding-left: 20px;
            margin: 10px;
        }

        .x-view-selector {
            position: absolute;
            left: 0;
            top: 0;
            width: 0;
            border: 1px dotted;
            opacity: .5;
            -moz-opacity: .5;
            filter: alpha(opacity=50);
            zoom: 1;
            background-color: #c3daf9;
            border-color: #3399bb;
        }

        .ext-strict .ext-ie .x-tree .x-panel-bwrap {
            position: relative;
            overflow: hidden;
        }
    </style>
</head>
<body>
    <script type="text/javascript" src="<?php echo $this->extjs; ?>"></script>
    <script type="text/javascript" src="<?php echo $this->extver; ?>components/BubbleMsg/Ext.BubbleMsg.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->extlang; ?>"></script>
    <script type="text/javascript" src="<?php echo $this->viewjs; ?>/views/lang/<?php echo $this->lang; ?>/sociocomercial.js"></script>
    <script type="text/javascript" src="<?php echo $this->extver; ?>ext/fn-utiles.js"></script>
    <script type="text/javascript" src="<?php echo $this->libjs; ?>Utils/Base64cypt.js"></script>
    <script type="text/javascript" src="<?php echo $this->viewjs; ?>/views/js/sociocomercial/appsociocomercial.js"></script>
    <!--Upload File para la foto del cliente o proveedor-->
    <input id="uploadFoto" type="file" style="visibility:hidden"/>
    <!--Upload File para la foto del contacto-->
    <input id="uploadFoto_contacto" type="file" style="visibility:hidden"/>
</body>
</html>