<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title><?php echo $this->appname; ?></title>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->extcss; ?>"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->libjs; ?>Extjs/2.2/resources/css/login.css"/>	
        <link rel="stylesheet" type="text/css" href="<?php echo $this->libjs; ?>Extjs/2.2/resources/css/login-tree<?php echo $this->theme; ?>.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->libcss; ?>fonts/FontAwesome/css/font-awesome.min.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->libjs; ?>Extjs/2.2/resources/css/iconos<?php echo $this->theme; ?>.css"/>	
        <link rel="stylesheet" type="text/css" href="<?php echo $this->libjs; ?>Extjs/2.2/resources/css/data-view.css"/>	
    </head>
    <body>
        <script type="text/javascript" src="<?php echo $this->viewjs; ?>/views/lang/<?php echo $this->lang; ?>/reindex.js"></script>
        <div class="container-fluid">
            <div class="row">
                <table id="tablaindex" width="100%" height="100%">
                    <tr>
                        <td align="center" valign="middle">
                            <div id="formIndex"></div>
                        </td>
                    </tr>
                </table>        
            </div>
        </div>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Jquery/jquery-1.11.1.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/ext/ext-jquery-adapter.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/ext/ext-base.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/ext/ext-all.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/lang/ext-lang-<?php echo $this->lang; ?>.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/ext/funciones-utiles.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Utils/md5.js"></script>
        <script type="text/javascript" src="<?php echo $this->viewjs; ?>/views/js/index/reindex.min.js"></script>
    </body>
</html>
