<!--<!DOCTYPE html>-->
<html>
    <head>
        <meta charset="UTF-8" />
        <link rel="stylesheet" type="text/css" href="<?php echo $this->extcss; ?>"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->libcss; ?>ff/matrix.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->extver; ?>components/BubbleMsg/Ext.BubbleMsg.min.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->libcss; ?>fonts/FontAwesome/css/font-awesome.min.css"/>
    </head>
    <body>
        <script type="text/javascript" src="<?php echo $this->extjs; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->extlang; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->extver; ?>components/BubbleMsg/Ext.BubbleMsg.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->extver; ?>ext/fn-utiles.js"></script>
        <script type="text/javascript" src="<?php echo $this->viewjs; ?>/views/js/seleccion/app.js"></script>
    </body>
</html>