<!--<!DOCTYPE html>-->
<html>
<head>
<meta charset="UTF-8" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->libjs; ?>Extjs/2.2/resources/css/ext-all.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->libjs; ?>Extjs/2.2/resources/css/iconos.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->libcss; ?>fonts/FontAwesome/css/font-awesome.min.css"/>
</head>
<body>
<script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/ext/ext-base.js"></script>
<script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/ext/ext-all.js"></script>
<script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/lang/ext-lang-es.js"></script>
<script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/ext/funciones-utiles.js"></script>
<script type="text/javascript" src="<?php echo $this->viewjs; ?>/views/js/planmantenimiento/planmantenimiento.js"></script>
</body>
</html>