
<html>
    <head>
        <meta charset="UTF-8" />
        <title></title>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->extcss; ?>"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->libcss; ?>ff/matrix.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->libcss; ?>fonts/FontAwesome/css/font-awesome.min.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->libjs; ?>Extjs/2.2/resources/css/colorfila.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->libjs; ?>Extjs/2.2/components/grid/RowEditor/css/RowEditor.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->libjs; ?>Extjs/2.2/components/form/Spinner/spinner.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->libjs; ?>Extjs/2.2/resources/css/file-upload.css"/>
    </head>
    <body>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/ext/ext-base.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/ext/ext-all.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/components/form/Spinner/Spinner.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/components/form/Spinner/SpinnerField.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/components/grid/RowActionColumn/Ext.grid.RowActions.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/components/grid/RowEditor/RowEditor.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/lang/ext-lang-<?php echo $this->lang; ?>.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/components/grid/PagingToolbar/Ext.Feet.PagingToolbar.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/components/form/SearchField/Ext.form.SearchField.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/ext/funciones-utiles.js"></script>
        <script type="text/javascript" src="<?php echo $this->viewjs; ?>/views/lang/<?php echo $this->lang; ?>/adminpedido.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/components/form/FileUploadField/FileUploadField.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->comun; ?>PrintView/views/js/Ext.PrintData.js"></script>
        <script type="text/javascript" src="<?php echo $this->viewjs; ?>/views/js/importpedido/Pedido.Class.js"></script>
        <script type="text/javascript" src="<?php echo $this->viewjs; ?>/views/js/importpedido/Pedido.UI.js"></script>
        <script type="text/javascript" src="<?php echo $this->viewjs; ?>/views/js/adminpedido/pedido.cor.js"></script>
        <script type="text/javascript" src="<?php echo $this->viewjs; ?>/views/js/adminpedido/pedido.pre.js"></script>
        <script type="text/javascript" src="<?php echo $this->viewjs; ?>/views/js/adminpedido/pedido.her.js"></script>
        <script type="text/javascript" src="<?php echo $this->viewjs; ?>/views/js/adminpedido/pedido.pro.js"></script>
        <script type="text/javascript" src="<?php echo $this->viewjs; ?>/views/js/adminpedido/main.js"></script>


    </body>
</html>
