<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title><?php echo $this->appname; ?></title>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->extcss; ?>"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->libjs; ?>Extjs/2.2/resources/css/login.css"/>	
        <link rel="stylesheet" type="text/css" href="<?php echo $this->libjs; ?>Extjs/2.2/resources/css/login-tree.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->libcss; ?>fonts/FontAwesome/css/font-awesome.min.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->libjs; ?>Extjs/2.2/resources/css/iconos.css"/>	
        <link rel="stylesheet" type="text/css" href="<?php echo $this->libjs; ?>Extjs/2.2/resources/css/colorfila.css"/>	
        <link rel="stylesheet" type="text/css" href="<?php echo $this->libjs; ?>Extjs/2.2/resources/css/data-view.css"/>	
        <link rel="shortcut icon" href="<?php echo $this->libjs; ?>Extjs/2.2/resources/images/icon/favicon.ico"/>
    </head>
    <body>
        <table id="tablaindex" width="100%" height="100%">
            <tr>
                <td align="center" valign="middle">
                    <div id="formIndex"> 
                        <div id="login" class="login">
                            <div id="backgrond">
                                <h1></h1>
                                <form name="loginform" id="loginform" action="javascript:validarCampos()" method="post">
                                    <br>
                                    <div class="inner">
                                        <div class="input-icon">
                                            <i class="fa fa-user"></i>
                                            <input id="loginuser" name="user" placeholder="Usuario" maxlength="30" onkeypress=" if (event.charCode != 0) {
                                                        return maskReg('loginuser', event.charCode, regexuser);
                                                    }" onkeyup="if (event.keyCode != 13)
                                                                javascript:quitInvalid('loginuser');" type="text" maxlength="20">
                                        </div>
                                    </div>
                                    <br>
                                    <div class="inner">
                                        <div class="input-icon">
                                            <i class="fa fa-lock"></i>
                                            <input id="loginpass" name="pass" placeholder="Contrase&ntilde;a" maxlength="50" onkeypress="if (event.charCode != 0) {
                                                        return maskReg('loginpass', event.charCode, regexpass);
                                                    }" onkeyup="if (event.keyCode != 13)
                                                                javascript:quitInvalid('loginpass');" type="password" maxlength="20">
                                        </div>
                                    </div>
                                    <br>
                                    <div class="inner">
                                        <button type="submit" class="btn btn-default">Acceder</button>
                                    </div>
                                </form>
                            </div>	
                        </div>
                    </div>
                </td>
            </tr>
        </table>        
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Jquery/jquery-1.11.1.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/ext/ext-jquery-adapter.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/ext/ext-base.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/ext/ext-all.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/lang/ext-lang-<?php echo $this->lang; ?>.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/ext/funciones-utiles.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Utils/md5.js"></script>
        <script type="text/javascript" src="<?php echo $this->viewjs; ?>/views/js/index/expired.min.js"></script>
    </body>
</html>
