<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title></title>
        <link rel="stylesheet" type="text/css" href="<?php echo $_REQUEST['comun'] . 'resources/css/ext-all.css'; ?>"/>	
        <link rel="stylesheet" type="text/css" href="<?php echo $_REQUEST['comun'] . 'resources/fonts/FontAwesome/css/font-awesome.min.css'; ?>"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $_REQUEST['comun'] . 'resources/css/iconos.css'; ?>"/>	
    </head>
    <body>
        <script language="javascript" type="text/javascript">function blank_image() {
                        return '<?php echo $_REQUEST['comun'] . 'resources/images/s.gif'; ?>';
                    }</script>
        <script type="text/javascript" src="<?php echo $_REQUEST['comun'] . 'ext/ext-base.js'; ?>"></script>
        <script type="text/javascript" src="<?php echo $_REQUEST['comun'] . 'ext/ext-all.js'; ?>"></script>
        <script type="text/javascript" src="<?php echo $_REQUEST['comun'] . 'ext/ext-lang-sp.js'; ?>"></script>
        <script type="text/javascript" src="<?php echo $_REQUEST['comun'] . 'ext/funciones-utiles.js'; ?>"></script>
        <script type="text/javascript" src="<?php echo $_REQUEST['comun'] . 'ext/Ext.Feet.PagingToolbar.js'; ?>"></script>
        <script type="text/javascript" src="<?php echo $_REQUEST['comun'] . 'ext/Ext.form.SearchField.js'; ?>"></script>
        <script type="text/javascript" src="<?php echo $_REQUEST['js'] . '/views/js/organismo/organismo.js'; ?>"></script>
    </body>
</html>
