<!--<!DOCTYPE html>-->
<html>
    <head>
        <meta charset="UTF-8" />
        <link rel="stylesheet" type="text/css" href="<?php echo $this->extcss; ?>"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->libjs; ?>Extjs/2.2/resources/css/iconos<?php echo $this->theme; ?>.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->libcss; ?>fonts/FontAwesome/css/font-awesome.min.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->libjs; ?>Extjs/2.2/components/grid/RowEditor/css/RowEditor.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->libjs; ?>Bootstrap/css/bootstrap-elements.css"/>
    </head>
    <body>
        <script type="text/javascript" src="<?php echo $this->viewjs; ?>/views/lang/<?php echo $this->lang; ?>/operaciones.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/ext/ext-base.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/ext/ext-all.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/lang/ext-lang-<?php echo $this->lang; ?>.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/ext/funciones-utiles.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/components/form/SearchField/Ext.form.SearchField.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/components/grid/PagingToolbar/Ext.Feet.PagingToolbar.min.js"></script>
        <script id="PrintView" type="text/javascript" src="<?php echo $this->comun; ?>PrintView/views/js/Ext.PrintView.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->viewjs; ?>/views/js/operaciones/operaciones.grid.js"></script>
        <script type="text/javascript" src="<?php echo $this->viewjs; ?>/views/js/operaciones/operaciones.window.js"></script>
        <script type="text/javascript" src="<?php echo $this->viewjs; ?>/views/js/operaciones/operaciones.app.js"></script>
    </body>
</html>