<html>
    <head>
        <meta charset="UTF-8" />
        <title>Instalaci&oacute;n del sistema</title>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->libjs; ?>Extjs/2.2/resources/css/ext-all.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->libcss; ?>fonts/FontAwesome/css/font-awesome.min.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->libjs; ?>Extjs/2.2/resources/css/iconos.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->libjs; ?>Bootstrap/css/bootstrap-elements.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->libjs; ?>Extjs/2.2/resources/css/installer.css"/>
    </head>
    <body>
        <table id="tablaindex" width="100%" height="100%">
            <tr>
                <td align="center" valign="middle">
                    <div id="render-wizard"></div>
                </td>
            </tr>
        </table>
        <script type="text/javascript">var dirApplication = "<?php echo $this->dirapp; ?>";</script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Jquery/jquery-1.11.1.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/ext/ext-jquery-adapter.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/ext/ext-base.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/ext/ext-all.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/lang/ext-lang-<?php echo $this->lang; ?>.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Extjs/2.2/ext/funciones-utiles.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Utils/Base64cypt.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Utils/md5.js"></script>
        <script type="text/javascript" src="<?php echo $this->libjs; ?>Bootstrap/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->viewjs; ?>/views/js/install/install.js"></script>
    </body>
</html>