<!DOCTYPE html>
<html>
    <head>
        <title>System error</title>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
        <meta content="Plataforma web" name="description"/>
        <meta content="GESI Solution's Group" name="author"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="/lib/css/fonts/FontAwesome/css/font-awesome.min.css" type="text/css"/>
        <link rel="stylesheet" href="/lib/js/Bootstrap/css/bootstrap.css" type="text/css"/>
        <link rel="stylesheet" href="/lib/css/ff/error.css" type="text/css"/>
    </head>
    <body class="page-500-full-page">
        <div class="container">
            <div class="content">
                <div class="row">
                    <div class="panel panel-danger">
                        <div class="panel-heading"><i class="fa fa-home"></i> Error interno del servidor</div>
                        <div class="col-sm-12 page-500">
                            <div class="errorsystem">
                                ERROR
                            </div>
                            <div class="details">
                                <h3>¡Uups! Error interno del servidor.</h3>
                                <p>
                                    Por favor, vuelva a intentarlo m&aacute;s tarde o contacte al administrador.<br/>
                                    A continuaci&oacute;n los detalles:<br/>
                                </p>
                            </div>
                        </div>
                        <div class="panel-body">
                            _error
                        </div>
                        <div class="panel-footer">
                            <center><a class="btn btn-danger" href="/" data-toggle="tooltip" data-placement="bottom" title="Regresar a la p&aacute;gina de inicio"><i class="fa fa-home"></i> INICIO</a></center>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script src="/lib/js/Jquery/jquery-1.11.1.min.js" language="javascript" type="text/javascript"></script>
        <script src="/lib/js/Bootstrap/js/bootstrap.min.js" language="javascript" type="text/javascript"></script>
        <script type="text/javascript">
            $(document).ready(function () {
                $('[data-toggle=tooltip]').tooltip();
            });
        </script>
    </body>
</html>
